# Generated by Django 4.1.2 on 2022-10-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budgettable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('updated_on', models.DateTimeField()),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('what_is', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='budget_table',
        ),
    ]
