# Generated by Django 4.1.2 on 2022-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0002_budgettable_delete_budget_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettable',
            name='currency',
            field=models.CharField(default='RUB', max_length=10),
            preserve_default=False,
        ),
    ]
