# Generated by Django 4.1.2 on 2022-11-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0004_budgettable_creator_budgettable_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgettable',
            name='creator',
            field=models.CharField(default='familyenter', max_length=100),
        ),
        migrations.AlterField(
            model_name='budgettable',
            name='updater',
            field=models.CharField(default='familyenter', max_length=100),
        ),
    ]
