# Generated by Django 4.1.2 on 2022-11-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0005_alter_budgettable_creator_alter_budgettable_updater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(default='familyenter', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updater', models.CharField(default='familyenter', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('what_is', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Budgettable',
        ),
    ]
