# Generated by Django 4.1.2 on 2022-11-24 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0006_budget_delete_budgettable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(default='familyenter', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creators', to='budget_db.familymembers'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_db.currency'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_db.section'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editors', to='budget_db.familymembers'),
        ),
    ]
