# Generated by Django 4.1.2 on 2022-11-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0008_alter_familymembers_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='updater',
        ),
        migrations.AddField(
            model_name='budget',
            name='editor',
            field=models.CharField(default='familyenter', max_length=100),
        ),
        migrations.AlterField(
            model_name='budget',
            name='creator',
            field=models.CharField(default='familyenter', max_length=100),
        ),
        migrations.DeleteModel(
            name='FamilyMembers',
        ),
    ]
