# Generated by Django 4.1.2 on 2022-11-24 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0009_remove_budget_updater_budget_editor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='editor',
            new_name='updater',
        ),
    ]
