# Generated by Django 4.1.2 on 2022-11-24 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0010_rename_editor_budget_updater'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.CharField(default='familyenter', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='budget',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
