# Generated by Django 4.1.2 on 2022-11-24 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_db', '0011_familymembers_alter_budget_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creators', to='budget_db.familymembers'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_db.currency'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_db.section'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='updater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='editors', to='budget_db.familymembers'),
        ),
    ]
