# Generated by Django 4.1.2 on 2022-10-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='budget_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField()),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('what_is', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
            ],
        ),
    ]
