# Generated by Django 4.1.2 on 2022-11-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetdb', '0003_budgettable_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgettable',
            name='creator',
            field=models.CharField(default='familyenter', max_length=20),
        ),
        migrations.AddField(
            model_name='budgettable',
            name='updater',
            field=models.CharField(default='familyenter', max_length=20),
        ),
    ]
